### ISSUE TITLE
Doesn't resolve host names, fails silently

### ISSUE THREAD

**Issue by atombender** [erikogan/wait4ports#1]
This tool doesn't explain that it requires an IP address, not a host name.

It uses `inet_aton()` without checking the return value, which means it just fails silently if you provide something like `tcp://postgres:5432`.

This means it's practically unusable with Docker Compose, where the IP of your network peers (e.g. PostgreSQL) is not known.

**Comment by erikogan** [comment]
While I agree with you that the tool should (optionally) do a host lookup, it was originally built for an older version of docker-compose that _only_ passed this information via environment variables. 

Unless I am mistaken, those environment variables are still available even with newer version configuration files. In your case the invocation might have been something like: `wait4ports postgres=$POSTGRES_PORT_5432_TCP`. 

Are working on submitting a patch to address this issue, or should I dig into it?

**Comment by erikogan** [comment]
It would appear that [I’m wrong about the environment variables still being set](https://docs.docker.com/compose/link-env-deprecated/). I suspect that was done deliberately to make links less static than they were in v1.

I’m currently out-of-town at a funeral, if you haven’t submitted anything by the time I return this weekend, I’ll dig into it then.

**Comment by atombender** [comment]
Awesome, thanks!
